version: "2.4"

services:
  pingaccess:
    image: ${REGISTRY}/pingaccess:${PINGACCESS_LATEST}-alpine-az11-${GIT_TAG}
    command: wait-for pingfederate:9031 -t 900 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_PATH=baseline/pingaccess
      - PA_ADMIN_PRIVATE_HOSTNAME=pingaccess
      - PF_ADMIN_PRIVATE_PORT_HTTPS=9999
    env_file:
      - /tmp/integration_tests.properties
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    memswap_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    oom_kill_disable: true
    mem_swappiness: 0
    tmpfs: /run/secrets
    networks:
      - pingnet-dmz
      - pingnet-internal
    depends_on:
      - pingfederate
      - pingdirectory

  pingfederate:
    image: ${REGISTRY}/pingfederate:${PINGFEDERATE_LATEST}-alpine-az11-${GIT_TAG}
    command: wait-for pingdirectory:389 -t 900 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_PATH=baseline/pingfederate
    env_file:
      - /tmp/integration_tests.properties
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    memswap_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    oom_kill_disable: true
    mem_swappiness: 0
    tmpfs: /run/secrets
    networks:
      - pingnet-dmz
      - pingnet-internal
    depends_on:
      - pingdirectory

  pingdirectory:
    image: ${REGISTRY}/pingdirectory:${PINGDIRECTORY_LATEST}-alpine-az11-${GIT_TAG}
    environment:
      - SERVER_PROFILE_PATH=baseline/pingdirectory
      - MAX_HEAP_SIZE=768m
    env_file:
      # Property file below provides common environment variables for all integration_tests.
      # run_integration.sh creates /tmp/integration_tests.properties at runtime.
      - /tmp/integration_tests.properties
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    memswap_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    mem_swappiness: 0
    tmpfs: /run/secrets
    networks:
      - pingnet-internal

  httpbin:
    image: ${DEPS}kennethreitz/httpbin
    ports:
      - "80:80"
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: 64m
    memswap_limit: 64m
    mem_swappiness: 0
    networks:
      - pingnet-internal

  sut:
    image: ${DEPS}postman/newman
    entrypoint: ["/usr/bin/env"]
    command: sh -c "/tmp/wait-for pingaccess:3000 -t 900 -- newman run /tmp/collection.json --insecure --ignore-redirects"
    volumes:
      - ./pa-pf-pd.postman_collection.json:/tmp/collection.json
      - ./wait-for:/tmp/wait-for
    depends_on:
      - pingaccess
      - pingfederate
      - pingdirectory
    networks:
      - pingnet-dmz
      - pingnet-internal

networks:
    pingnet-internal:
    pingnet-dmz:
