version: "2.4"

services:
  pingaccess:
    image: ${REGISTRY}/pingaccess:${PINGACCESS_LATEST}-${SHIM}-${JVM}-${GIT_TAG}-${ARCH}
    command: wait-for pingfederate:9031 -t 2100 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_PATH=baseline/pingaccess
      - SERVER_PROFILE_BRANCH=FIPS
      - PA_ADMIN_PRIVATE_HOSTNAME=pingaccess
      - PF_ADMIN_PRIVATE_PORT_HTTPS=9999
      - FIPS_MODE_ON=true
    env_file:
      - /tmp/integration_tests.properties
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    memswap_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    oom_kill_disable: true
    mem_swappiness: 0
    tmpfs: /run/secrets
    networks:
      - pingnet-dmz
      - pingnet-internal
    depends_on:
      - pingfederate
      - pingdirectory

  pingfederate:
    image: ${REGISTRY}/pingfederate:${PINGFEDERATE_LATEST}-${SHIM}-${JVM}-${GIT_TAG}-${ARCH}
    command: wait-for pingdirectory:1636 -t 1800 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_PATH=baseline/pingfederate
      - SERVER_PROFILE_BRANCH=FIPS
      - LDAP_PORT=1636
      # In addition to setting HSM_MODE to BCFIPS you will also need:
      #   update hivemodule.xml 
      #    JCEManager         => com.pingidentity.crypto.BCFIPSJCEManager
      #    CertificateService => com.pingidentity.crypto.BCFIPSCertificateServiceImpl
      - HSM_MODE=BCFIPS
    env_file:
      - /tmp/integration_tests.properties
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    memswap_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    oom_kill_disable: true
    mem_swappiness: 0
    tmpfs: /run/secrets
    networks:
      - pingnet-dmz
      - pingnet-internal
    depends_on:
      - pingdirectory

  pingdirectory:
    image: ${REGISTRY}/pingdirectory:${PINGDIRECTORY_LATEST}-${SHIM}-${JVM}-${GIT_TAG}-${ARCH}
    environment:
      - SERVER_PROFILE_PATH=baseline/pingdirectory
      - SERVER_PROFILE_BRANCH=FIPS
      - MAX_HEAP_SIZE=1g
      - FIPS_MODE_ON=true
      - KEYSTORE_FILE=/opt/staging/.sec/private-key.pem
      - KEYSTORE_TYPE=pem
      - TRUSTSTORE_FILE=/opt/staging/.sec/certificate-chain.pem
      - TRUSTSTORE_TYPE=pem
      - CERTIFICATE_NICKNAME=server-cert
    env_file:
      # Property file below provides common environment variables for all integration_tests.
      # run_integration.sh creates /tmp/integration_tests.properties at runtime.
      - /tmp/integration_tests.properties
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    memswap_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    mem_swappiness: 0
    tmpfs: /run/secrets
    networks:
      - pingnet-internal

  httpbin:
    image: ${DEPS}arnaudlacour/httpbin
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: 64m
    memswap_limit: 64m
    mem_swappiness: 0
    networks:
      - pingnet-internal

  sut:
    image: ${DEPS}arnaudlacour/newman
    entrypoint: ["/usr/bin/env"]
    command: sh -c "/tmp/wait-for pingaccess:3000 -t 2400 -- newman run /tmp/collection.json --insecure --ignore-redirects"
    volumes:
      - ./pa-pf-pd-FIPS.postman_collection.json:/tmp/collection.json
      - ./wait-for:/tmp/wait-for
    depends_on:
      - pingaccess
      - pingfederate
      - pingdirectory
    networks:
      - pingnet-dmz
      - pingnet-internal

networks:
    pingnet-internal:
    pingnet-dmz:
