version: "2.4"

services:
  pingdirectory:
    image: ${REGISTRY}/pingdirectory:${PINGDIRECTORY_LATEST}-${PINGDIRECTORY_SHIM}-${JVM}-${GIT_TAG}-${ARCH}
    environment:
      - SERVER_PROFILE_PATH=baseline/pingdirectory
      - MAX_HEAP_SIZE=768m
    env_file:
      - /tmp/integration_tests.properties
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    memswap_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    mem_swappiness: 0
    tmpfs: /run/secrets

  pingdirectoryproxy:
    image: ${REGISTRY}/pingdirectoryproxy:${PINGDIRECTORYPROXY_LATEST}-${PINGDIRECTORYPROXY_SHIM}-${JVM}-${GIT_TAG}-${ARCH}
    command: wait-for pingdirectory:1389 -t 900 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_PATH=baseline/pingdirectoryproxy
    env_file:
      # Property file below provides common environment variables for all integration_tests.
      # run_integration.sh creates /tmp/integration_tests.properties at runtime.
      - /tmp/integration_tests.properties
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    memswap_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    oom_kill_disable: true
    mem_swappiness: 0
    tmpfs: /run/secrets
    depends_on: ["pingdirectory"]

  sut:
    image: ${DEPS}arnaudlacour/newman
    entrypoint: ["/usr/bin/env"]
    command: sh -c "/tmp/wait-for pingdirectoryproxy:1389 -t 900 -- newman run /tmp/collection.json --insecure --ignore-redirects"
    volumes:
      - ./pdp-pd.postman_collection.json:/tmp/collection.json
      - ./wait-for:/tmp/wait-for
    depends_on: ["pingdirectoryproxy"]
