################################################
#                  BUILD 
################################################

intel.b.pingintelligence:
  stage: products
  script:
    - ci_scripts/build_product.sh --product pingintelligence
  only:
    changes:
      - integration_tests/pi-*
      - pingintelligence/**/*
      - pingcommon/**/*
      - pingbase/**/*
      - pingdownloader/**/*
      - ci_scripts/*
      - .gitlab-ci.yml
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^workspace.*/
      - $CI_COMMIT_MESSAGE =~ /\[skip build\]/
      - $CI_COMMIT_MESSAGE =~ /\[skip products\]/
      - $PING_IDENTITY_SNAPSHOT =~ /--snapshot/
      - $BUILD_PRODUCT && $BUILD_PRODUCT !~ /(?:^|,)pingintelligence(?:$|,)/i

################################################
#                  SMOKE TESTS
################################################

intel.t.pingintelligence:
  stage: test.smoke
  script:
    - ci_scripts/run_smoke.sh --product pingintelligence
  only:
    changes:
      - integration_tests/pi-*
      - pingintelligence/**/*
      - pingcommon/**/*
      - pingbase/**/*
      - pingdownloader/**/*
      - ci_scripts/*
      - .gitlab-ci.yml
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^workspace.*/
      - $CI_COMMIT_MESSAGE =~ /\[skip build\]/
      - $CI_COMMIT_MESSAGE =~ /\[skip products\]/
      - $CI_COMMIT_MESSAGE =~ /\[skip tests\]/
      - $CI_COMMIT_MESSAGE =~ /\[skip smoke\]/
      - $PING_IDENTITY_SNAPSHOT =~ /--snapshot/
      - $BUILD_PRODUCT && $BUILD_PRODUCT !~ /(?:^|,)pingintelligence(?:$|,)/i

################################################
#                  DEPLOY
################################################

d.pingintelligence:
  stage: deploy
  script:
    - ci_scripts/deploy_product_to_registry.sh --product pingintelligence
    - ci_scripts/deploy_manifests_to_registry.sh --product pingintelligence
  only:
    refs:
      - master
      - tags
    changes:
      - pingintelligence/**/*
      - pingcommon/**/*
      - pingbase/**/*
      - ci_scripts/*
      - .gitlab-ci.yml
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^workspace.*/
      - $CI_COMMIT_MESSAGE =~ /\[skip build\]/
      - $CI_COMMIT_MESSAGE =~ /\[skip products\]/
      - $CI_COMMIT_MESSAGE =~ /\[skip deploy\]/
      - $PING_IDENTITY_SNAPSHOT =~ /--snapshot/
      - $BUILD_PRODUCT && $BUILD_PRODUCT !~ /(?:^|,)pingintelligence(?:$|,)/i
