################################################
#                  DEPLOY
################################################

d.pingdownloader:
  stage: deploy
  script:
    - ci_scripts/deploy_product_to_registry.sh --product pingdownloader
    - ci_scripts/deploy_manifests_to_registry.sh --product pingdownloader
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip deploy\]/i'
      when: never
    - if: '$PING_IDENTITY_SNAPSHOT =~ /--snapshot/'
      when: never
    - if: '$CI_COMMIT_REF_NAME =~ /^master$/'
      changes:
        - pingdownloader/**/*
        - ci_scripts/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_COMMIT_TAG =~ /^\d{4}$/'
      when: on_success
