################################################
# The purpose of the integration test below is
# to verify replication between two
# instances of PingDirectory with the latest
# release for the liberica JVM on the x86_64 runner
intel.pd-repl.liberica:
  stage: test.integration
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pd-replicated --image-tag-jvm al11 --image-tag-arch x86_64
  retry: 1
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 3920000000
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip integration\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingdirectory(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - helm-tests/integration-tests/pd-replicated/*
        - pingbase/**/*
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingdirectory/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
# The purpose of the integration test below is
# to verify replication between two
# instances of PingDirectory with the latest
# release for the liberica JVM on the aarch64 runner
arm.pd-repl.liberica:
  stage: test.integration
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pd-replicated --image-tag-jvm al11 --image-tag-arch aarch64
  retry: 1
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 5880000000
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip integration\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingdirectory(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - helm-tests/integration-tests/pd-replicated/*
        - pingbase/**/*
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingdirectory/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
# The purpose of the integration test below is
# to verify PingAccess, PingFederate and PingDirectory
# integrate together into an end to end test
# for the liberica x86 JVM on a RHEL shim in
# FIPS mode
#intel.pa-pf-pd-fips.liberica:
#  stage: test.integration
#  script:
#    - ci_scripts/run_helm_integration.sh --integration-test pa-pf-pd-fips --image-tag-jvm rl11
#  retry: 1
#  variables:
#    KUBERNETES_CPU_REQUEST: 2850m
#    KUBERNETES_CPU_LIMIT: 2850m
#    KUBERNETES_MEMORY_REQUEST: 1960000000
#    KUBERNETES_MEMORY_LIMIT: 1960000000
#  rules:
#    - if: $ARCHIVE_PIPELINE == "true"
#      when: never
#    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip integration\]/i'
#      when: never
#    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingaccess(?:$|,)/i && $BUILD_PRODUCT =~ /(?:^|,)pingdirectory(?:$|,)/i && $BUILD_PRODUCT =~ /(?:^|,)pingfederate(?:$|,)/i'
#      when: on_success
#    - if: '$BUILD_PRODUCT != null'
#      when: never
#    - if: '$PING_IDENTITY_SNAPSHOT =~ /--snapshot/'
#      when: never
#    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
#      changes:
#        - helm-tests/integration-tests/pa-pf-pd-fips/*
#        - pingbase/**/*
#        - pingcommon/**/*
#        - pingdatacommon/**/*
#        - pingaccess/**/*
#        - pingdirectory/**/*
#        - pingfederate/**/*
#        - ci_scripts/*
#        - pingjvm/*
#        - .gitlab-ci.yml
#      when: on_success
#    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
#      when: on_success

################################################
# The purpose of the integration test below is
# to verify PingAccess, PingFederate and PingDirectory
# integrate together into an end to end test
# for the liberica JVM on the x86_64 runner
intel.pa-pf-pd.liberica:
  stage: test.integration
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pa-pf-pd --image-tag-jvm al11 --image-tag-arch x86_64
  retry: 1
  variables:
    KUBERNETES_CPU_REQUEST: 2850m
    KUBERNETES_CPU_LIMIT: 2850m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 3920000000
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip integration\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingaccess(?:$|,)/i && $BUILD_PRODUCT =~ /(?:^|,)pingdirectory(?:$|,)/i && $BUILD_PRODUCT =~ /(?:^|,)pingfederate(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - helm-tests/integration-tests/pa-pf-pd/*
        - pingbase/**/*
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingaccess/**/*
        - pingdirectory/**/*
        - pingfederate/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
# The purpose of the integration test below is
# to verify PingAccess, PingFederate and PingDirectory
# integrate together into an end to end test
# for the liberica JVM on the aarch64 runner
arm.pa-pf-pd.liberica:
  stage: test.integration
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pa-pf-pd --image-tag-jvm al11 --image-tag-arch aarch64
  retry: 1
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 5880000000
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip integration\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingaccess(?:$|,)/i && $BUILD_PRODUCT =~ /(?:^|,)pingdirectory(?:$|,)/i && $BUILD_PRODUCT =~ /(?:^|,)pingfederate(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - helm-tests/integration-tests/pa-pf-pd/*
        - pingbase/**/*
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingaccess/**/*
        - pingdirectory/**/*
        - pingfederate/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
# The purpose of the integration test below is
# to verify PingDataSync and PingDirectory
# integrate together into an end to end test
# for the liberica JVM on the x86_64 runner
intel.pds-pd.liberica:
  stage: test.integration
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pds-pd --image-tag-jvm al11 --image-tag-arch x86_64
  retry: 1
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 3920000000
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip integration\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingdirectory(?:$|,)/i && $BUILD_PRODUCT =~ /(?:^|,)pingdatasync(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - helm-tests/integration-tests/pds-pd/*
        - pingbase/**/*
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingdirectory/**/*
        - pingdatasync/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success


################################################
# The purpose of the integration test below is
# to verify PingDataSync and PingDirectory
# integrate together into an end to end test
# for the liberica JVM on the aarch64 runner
arm.pds-pd.liberica:
  stage: test.integration
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pds-pd --image-tag-jvm al11 --image-tag-arch aarch64
  retry: 1
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 5880000000
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip integration\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingdirectory(?:$|,)/i && $BUILD_PRODUCT =~ /(?:^|,)pingdatasync(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - helm-tests/integration-tests/pds-pd/*
        - pingbase/**/*
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingdirectory/**/*
        - pingdatasync/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
# The purpose of the integration test below is
# to verify PingDirectoryProxy and PingDirectory
# integrate together into an end to end test
# for the liberica JVM on the x86_64 runner
intel.pdp-pd.liberica:
  stage: test.integration
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pdp-pd --image-tag-jvm al11 --image-tag-arch x86_64
  retry: 1
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 5880000000
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip integration\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingdirectory(?:$|,)/i && $BUILD_PRODUCT =~ /(?:^|,)pingdirectoryproxy(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - helm-tests/integration-tests/pdp-pd/*
        - pingbase/**/*
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingdirectory/**/*
        - pingdirectoryproxy/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
# The purpose of the integration test below is
# to verify PingDirectoryProxy and PingDirectory
# integrate together into an end to end test
# for the liberica JVM on the aarch64 runner
arm.pdp-pd.liberica:
  stage: test.integration
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pdp-pd --image-tag-jvm al11 --image-tag-arch aarch64
  retry: 1
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 3920000000
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip integration\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingdirectory(?:$|,)/i && $BUILD_PRODUCT =~ /(?:^|,)pingdirectoryproxy(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - helm-tests/integration-tests/pdp-pd/*
        - pingbase/**/*
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingdirectory/**/*
        - pingdirectoryproxy/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
# The purpose of the integration test below is
# to verify PingAuthorize and PingDirectory
# integrate together into an end to end test
# for the liberica JVM on the x86_64 runner
intel.paz-pd.liberica:
  stage: test.integration
  script:
    - ci_scripts/run_helm_integration.sh --integration-test paz-pd --image-tag-jvm al11 --image-tag-arch x86_64
  retry: 1
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 3920000000
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip integration\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingdirectory(?:$|,)/i && $BUILD_PRODUCT =~ /(?:^|,)pingauthorize(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - helm-tests/integration-tests/paz-pd/*
        - pingbase/**/*
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingdirectory/**/*
        - pingauthorize/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
# The purpose of the integration test below is
# to verify PingAuthorize and PingDirectory
# integrate together into an end to end test
# for the liberica JVM on the aarch64 runner
arm.paz-pd.liberica:
  stage: test.integration
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_integration.sh --integration-test paz-pd --image-tag-jvm al11 --image-tag-arch aarch64
  retry: 1
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 5880000000
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip integration\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingdirectory(?:$|,)/i && $BUILD_PRODUCT =~ /(?:^|,)pingauthorize(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - helm-tests/integration-tests/paz-pd/*
        - pingbase/**/*
        - pingcommon/**/*
        - pingdatacommon/**/*
        - pingdirectory/**/*
        - pingauthorize/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
# The purpose of the integration test below is
# to verify PingIntelligence
# works in an end to end test
# on the x86_64 runner
intel.pi-basic.latest:
  stage: test.integration
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pa-pf-pi
  retry: 1
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip integration\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)pingintelligence(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$PING_IDENTITY_SNAPSHOT =~ /--snapshot/'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - helm-tests/integration-tests/pa-pf-pi/*
        - pingbase/**/*
        - pingcommon/**/*
        - pingintelligence/**/*
        - ci_scripts/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success
