apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: haveged
  labels:
    app.kubernetes.io/name: haveged
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: haveged
  template:
    metadata:
      labels:
        app.kubernetes.io/name: haveged
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
        - name: haveged
          image: hortonworks/haveged:1.2.0
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]